services:
  ocr-service:
    build: ./ingestion-service
    container_name: ocr
    env_file:
      - ./config/.env
      - ./config/ocr.env
    volumes:
      - ./ingestion-service/app:/app
      - ./data:/data 
    deploy:
      resources:
        limits:
          cpus: '0.50' # מגביל את השירות לחצי ליבה בלבד
          memory: 512M
    depends_on:
      kafka:
        condition: service_healthy
      mongo:
        condition: service_started
    
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    ports:
      - "9092:9092"

    environment:
      KAFKA_KRAFT_MODE: 'true'

      CLUSTER_ID: '1L6g7nGhU-eAKfL--X25wo'
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - kafka_kraft:/var/lib/kafka/data
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  mongo_loader:
    build: ./mongo_loader
    container_name: mongo_loader 
    ports:
      - "8000:8000"
    env_file:
      - ./config/mongo_loader.env
    volumes:
      - ./mongo_loader/app:/app
      - ./data:/data 
    depends_on:
      mongo:
        condition: service_started
  cleaner_service:
    build: ./clean-service
    container_name: cleaner_service
    env_file:
      - ./config/clean_service.env
      - ./config/.env
    volumes:
      - ./clean-service/app:/app
      - ./shared:/shared
    working_dir: /app
    environment:
      - PYTHONPATH=/app:/
    depends_on:
      kafka:
        condition: service_healthy
  analyze-service:
    build: ./analytics-service
    container_name: analyze
    env_file:
      - ./config/analyze.env
      - ./config/.env
    volumes:
      - ./analytics-service/app:/app
      - ./shared:/shared
      - ./data:/data
    working_dir: /app
    environment:
      - PYTHONPATH=/app:/
    depends_on:
      kafka:
        condition: service_healthy
  elastic-service:
    build: ./elastic-service
    container_name: elastic
    env_file:
      - ./config/elastic.env
      - ./config/.env
    volumes:
      - ./elastic-service/app:/app
      - ./shared:/shared
    working_dir: /app
    environment:
      - PYTHONPATH=/app:/
    depends_on:
      kafka:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 20s
    volumes:
      - es_data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 1gb
volumes:
  kafka_kraft:
  mongo_data:
  es_data: